=begin
#FastAPI

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 0.1.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.46
=end

require 'date'

module Rauto1111AI
  class Estimation
    attr_accessor :msg

    attr_accessor :rank

    attr_accessor :queue_size

    attr_accessor :avg_event_process_time

    attr_accessor :avg_event_concurrent_process_time

    attr_accessor :rank_eta

    attr_accessor :queue_eta

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'msg' => :'msg',
        :'rank' => :'rank',
        :'queue_size' => :'queue_size',
        :'avg_event_process_time' => :'avg_event_process_time',
        :'avg_event_concurrent_process_time' => :'avg_event_concurrent_process_time',
        :'rank_eta' => :'rank_eta',
        :'queue_eta' => :'queue_eta'
      }
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'msg' => :'Object',
        :'rank' => :'Object',
        :'queue_size' => :'Object',
        :'avg_event_process_time' => :'Object',
        :'avg_event_concurrent_process_time' => :'Object',
        :'rank_eta' => :'Object',
        :'queue_eta' => :'Object'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end
  
    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `Rauto1111AI::Estimation` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `Rauto1111AI::Estimation`. Please check the name to make sure it's valid. List of attributes: " + self.class.attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'msg')
        self.msg = attributes[:'msg']
      else
        self.msg = 'estimation'
      end

      if attributes.key?(:'rank')
        self.rank = attributes[:'rank']
      end

      if attributes.key?(:'queue_size')
        self.queue_size = attributes[:'queue_size']
      end

      if attributes.key?(:'avg_event_process_time')
        self.avg_event_process_time = attributes[:'avg_event_process_time']
      end

      if attributes.key?(:'avg_event_concurrent_process_time')
        self.avg_event_concurrent_process_time = attributes[:'avg_event_concurrent_process_time']
      end

      if attributes.key?(:'rank_eta')
        self.rank_eta = attributes[:'rank_eta']
      end

      if attributes.key?(:'queue_eta')
        self.queue_eta = attributes[:'queue_eta']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      invalid_properties = Array.new
      if @queue_size.nil?
        invalid_properties.push('invalid value for "queue_size", queue_size cannot be nil.')
      end

      if @queue_eta.nil?
        invalid_properties.push('invalid value for "queue_eta", queue_eta cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      return false if @queue_size.nil?
      return false if @queue_eta.nil?
      true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          msg == o.msg &&
          rank == o.rank &&
          queue_size == o.queue_size &&
          avg_event_process_time == o.avg_event_process_time &&
          avg_event_concurrent_process_time == o.avg_event_concurrent_process_time &&
          rank_eta == o.rank_eta &&
          queue_eta == o.queue_eta
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [msg, rank, queue_size, avg_event_process_time, avg_event_concurrent_process_time, rank_eta, queue_eta].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      new.build_from_hash(attributes)
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      self.class.openapi_types.each_pair do |key, type|
        if type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            self.send("#{key}=", attributes[self.class.attribute_map[key]].map { |v| _deserialize($1, v) })
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          self.send("#{key}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
        elsif attributes[self.class.attribute_map[key]].nil? && self.class.openapi_nullable.include?(key)
          self.send("#{key}=", nil)
        end
      end

      self
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def _deserialize(type, value)
      case type.to_sym
      when :DateTime
        DateTime.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        Rauto1111AI.const_get(type).build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end  end
end
