=begin
#FastAPI

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 0.1.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.46
=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for RStableDiffusionAI::AnyOfPredictBodyRequest
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'AnyOfPredictBodyRequest' do
  before do
    # run before each test
    @instance = RStableDiffusionAI::AnyOfPredictBodyRequest.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of AnyOfPredictBodyRequest' do
    it 'should create an instance of AnyOfPredictBodyRequest' do
      expect(@instance).to be_instance_of(RStableDiffusionAI::AnyOfPredictBodyRequest)
    end
  end
end
