=begin
#FastAPI

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 0.1.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.46
=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for Rauto1111AI::HypernetworkItem
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'HypernetworkItem' do
  before do
    # run before each test
    @instance = Rauto1111AI::HypernetworkItem.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of HypernetworkItem' do
    it 'should create an instance of HypernetworkItem' do
      expect(@instance).to be_instance_of(Rauto1111AI::HypernetworkItem)
    end
  end
  describe 'test attribute "name"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "path"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
