=begin
#FastAPI

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 0.1.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.46
=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for RStableDiffusionAI::ScriptsList
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'ScriptsList' do
  before do
    # run before each test
    @instance = RStableDiffusionAI::ScriptsList.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ScriptsList' do
    it 'should create an instance of ScriptsList' do
      expect(@instance).to be_instance_of(RStableDiffusionAI::ScriptsList)
    end
  end
  describe 'test attribute "txt2img"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "img2img"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
