=begin
#FastAPI

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 0.1.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.46
=end

# Common files
require 'ruby-auto1111/api_client'
require 'ruby-auto1111/api_error'
require 'ruby-auto1111/version'
require 'ruby-auto1111/configuration'

# Models
require 'ruby-auto1111/models/any_of_predict_body_request'
require 'ruby-auto1111/models/any_of_validation_error_loc_items'
require 'ruby-auto1111/models/body_login_login__post'
require 'ruby-auto1111/models/body_upload_file_upload_post'
require 'ruby-auto1111/models/create_response'
require 'ruby-auto1111/models/embedding_item'
require 'ruby-auto1111/models/embeddings_response'
require 'ruby-auto1111/models/estimation'
require 'ruby-auto1111/models/extras_batch_images_request'
require 'ruby-auto1111/models/extras_batch_images_response'
require 'ruby-auto1111/models/extras_single_image_request'
require 'ruby-auto1111/models/extras_single_image_response'
require 'ruby-auto1111/models/face_restorer_item'
require 'ruby-auto1111/models/file_data'
require 'ruby-auto1111/models/flags'
require 'ruby-auto1111/models/http_validation_error'
require 'ruby-auto1111/models/hypernetwork_item'
require 'ruby-auto1111/models/image_to_image_response'
require 'ruby-auto1111/models/interrogate_request'
require 'ruby-auto1111/models/latent_upscaler_mode_item'
require 'ruby-auto1111/models/memory_response'
require 'ruby-auto1111/models/modules__api__models__progress_response'
require 'ruby-auto1111/models/modules__progress__progress_response'
require 'ruby-auto1111/models/options'
require 'ruby-auto1111/models/png_info_request'
require 'ruby-auto1111/models/png_info_response'
require 'ruby-auto1111/models/predict_body'
require 'ruby-auto1111/models/preprocess_response'
require 'ruby-auto1111/models/progress_request'
require 'ruby-auto1111/models/prompt_style_item'
require 'ruby-auto1111/models/quicksettings_hint'
require 'ruby-auto1111/models/realesrgan_item'
require 'ruby-auto1111/models/reset_body'
require 'ruby-auto1111/models/sd_model_item'
require 'ruby-auto1111/models/sd_vae_item'
require 'ruby-auto1111/models/sampler_item'
require 'ruby-auto1111/models/script_arg'
require 'ruby-auto1111/models/script_info'
require 'ruby-auto1111/models/scripts_list'
require 'ruby-auto1111/models/stable_diffusion_processing_img2_img'
require 'ruby-auto1111/models/stable_diffusion_processing_txt2_img'
require 'ruby-auto1111/models/text_to_image_response'
require 'ruby-auto1111/models/train_response'
require 'ruby-auto1111/models/upscaler_item'
require 'ruby-auto1111/models/validation_error'

# APIs
require 'ruby-auto1111/api/default_api'

module Rauto1111AI
  class << self
    # Customize default settings for the SDK using block.
    #   Rauto1111AI.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
